### ISSUE TITLE
구글 로그인 동의항목 체크 밑줄 강조

### ISSUE THREAD

**Issue by JJong84** [kezuler/kezuler#275]
## Related Link

[노션 카드](https://www.notion.so/92c8436a6eed410e84dfcdf67bbeabd6)

## Description

- 팝업에 부분 밑줄 처리가 가능하도록 구현해 구글 연동 팝업에 적용시킨다.

## Todo

- [ ] descrption 을 부분 밑줄 처리가 가능하도록 리스트 형태로 변경
- [ ] 밑줄이 추가될 부분인 google 연동 부분을 useConnectGoogle 로 묶어서 중복 코드 제거
- [ ] 밑줄 관련 css 추가
