### ISSUE TITLE
미팅생성 장소 step 줄이기

### ISSUE THREAD

**Issue by JJong84** [kezuler/kezuler#300]
## Related Link

[노션 링크](https://www.notion.so/step-72d202dafbe744ccbefdc127f09c5a5d)

## Description

- 미팅 생성 시 장소 선택을 첫번째로 옮긴다

## Todo

- [x] 장소 선택 컴포넌트, css, 주소 및 관련 로직 삭제
- [x] 첫번쨰 페이지에 장소 선택 로직 추가
- [ ] 첫번째 페이지 각 input 별로 컴포넌트화

## ETC
첫번째 페이지 코드가 길어져서 컴포넌트를 분리하겠습니다.
